name: Release Docker Image

on:
  workflow_dispatch: # for manual testing
  push:
    branches:
      - main

jobs:
  call-docker-release:
    permissions:
      contents: write
      packages: write
    uses: thealtoclef/modular-automations/.github/workflows/docker-release.yaml@main
    with:
      no_push: false
